FROM apache/flink:1.18.1-scala_2.12-java11-python

USER root
RUN set -eux; \
    wget -q -O /opt/flink/lib/flink-connector-kafka-3.0.2-1.18.jar \
      https://repo1.maven.org/maven2/org/apache/flink/flink-connector-kafka/3.0.2-1.18/flink-connector-kafka-3.0.2-1.18.jar; \
    wget -q -O /opt/flink/lib/flink-connector-jdbc-3.1.2-1.18.jar \
      https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.1.2-1.18/flink-connector-jdbc-3.1.2-1.18.jar; \
    wget -q -O /opt/flink/lib/postgresql-42.7.2.jar \
      https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.jar

WORKDIR /opt/flink/usrlib
COPY --chown=flink:flink streaming/job.py .
COPY --chown=flink:flink infra/railway/demo_entrypoint.sh /opt/flink/demo_entrypoint.sh
RUN chmod +x /opt/flink/demo_entrypoint.sh

USER flink
ENTRYPOINT ["/opt/flink/demo_entrypoint.sh"]
CMD ["python", "job.py"]
